title: Obsolism
email: N/A
description: >-
  An open-source religion for the digital age.
baseurl: ""
url: "https://obsolism.org"
github_repo: obsolism
github_username: obsolism

social_link: twitter
social_username: obsolism

# Build settings
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag

source: ./
exclude: [obsolism]

keep_files: [images]
