title: Obsolism
email: N/A
description: >-
  An open-source religion for the digital age.
baseurl: ""
url: "https://obsolism.org"
twitter_username: obsolism
github_username: obsolism

# Build settings
remote_theme: broccolini/swiss
plugins:
  - jekyll-feed
  - jekyll-seo-tag

source: ./obsolism

collections:
  posts:
    output: false
